name: clock
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - biopython=1.73
  - blast=2.7.1
  - clint=0.5.1=py36_0
  - coreutils=8.25
  - mafft
  - medaka=0.10.0
  - miniasm
  - minimap2=2.17
  - nanopolish
  - nodejs=12.12.0
  - npm=6.12.0
  - pandas=0.23.0=py36_1
  - pip=19.1
  - python=3.6
  - racon=1.4.7
  - samtools=1.9
  - seqtk=1.3
  - snakemake=5.4.3
  - watchdog=0.8.3=py36_0
  - pip:
    - binlorry==0.1
    - h5py==2.7.1 
    - matplotlib==3.1.1
    - msgpack==0.5.6
    - nextstrain-augur
    - numpy==1.16.1
    - git+https://github.com/artic-network/Porechop.git
    - scipy==1.3.1
    - seaborn
    - tensorflow==1.14.0
    
